const $=id=>document.getElementById(id);let state=null,index=-1,busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,data){const res=await fetch('/api/'+path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Kiodai-Demo':'1'},body:JSON.stringify(data)});const result=await res.json();if(!res.ok)throw Error(result.error);return result;}
function modeChanged(){const mode=$('mode').value;$('recordingLabel').hidden=mode!=='RECORDED';$('liveLabel').hidden=mode!=='LIVE';$('scenario').disabled=mode==='RECORDED';const shownMode=state?.has_run?state.mode:mode;$('modeBadge').textContent=shownMode;$('boundary').textContent=shownMode==='MOCK'?'MOCK uses identical scripted responses for both conditions. It tests the software, not the model.':shownMode==='RECORDED'?'RECORDED replays genuine saved LIVE artifacts. Advancing the timeline makes no model calls.':'LIVE makes paid requests to the pinned provider. It requires server opt-in and an explicit budget.';}
function render(){if(!state)return;$('modeBadge').textContent=state.mode;$('notice').textContent=state.notice||'Synthetic research scenarios · Local artifacts · No real messages or calendar changes';$('recording').innerHTML=state.recordings.map(r=>`<option value="${esc(r.id)}">${esc(r.title)}</option>`).join('')||'<option>No genuine saved live runs</option>';
const count=state.visible_steps||0;index=Math.min(index,count-1);$('stepSelect').innerHTML=Array.from({length:count},(_,i)=>`<option value="${i}">Step ${i+1}</option>`).join('');$('stepSelect').value=index;$('stepSelect').disabled=!count;$('next').disabled=busy||!state.has_run||!['running','replaying'].includes(state.status);$('reveal').disabled=busy||index<0;$('start').disabled=busy;$('reset').disabled=busy;$('export').hidden=!state.has_run;
$('progress').max=state.total_steps||1;$('progress').value=count;$('progressText').textContent=state.has_run?`${count} of ${state.total_steps} scheduled steps · ${state.status}`:'Select a scenario and start an offline run.';
$('time').textContent=state.conditions.A0?.steps[index]?.time||'Ready when you are';$('runDetails').textContent=state.has_run?`${state.mode} · ${state.pair_id} · saved after every step`:'No run saved yet.';
for(const cond of ['A0','A1']){const node=$(cond.toLowerCase()),c=state.conditions[cond],step=c?.steps[index];node.querySelector('.run-state').textContent=busy?'Working':c?.status||'Waiting';const body=node.querySelector('.agent-body');if(!step){body.innerHTML='<p class="empty">Advance the timeline to inspect the actual<br>agent request and its selected actions.</p>';continue;}
const calls=c.calls.filter(call=>call.call_context.day===step.day&&call.call_context.step_id===step.step_id);const selected=step.action.selected_handles_validated;const history=step.agent_messages.filter(m=>m.role==='user').at(-1)?.content||'';const labels=Object.fromEntries([...history.matchAll(/^- (task_\d+): (.+)$/gm)].map(m=>[m[1],m[2]]));body.innerHTML=`<div class="block"><p class="label">Current observation · ${esc(state.mode)}</p><div class="observations">${esc(history)}</div></div><div class="block"><p class="label">Selected actions</p><div class="action-text">${selected.length?selected.map(h=>esc(h+': '+(labels[h]||''))).join('<br>'):'∅  No task action'}</div><div class="outcome">${step.execution.length?step.execution.map(e=>`${esc(e.handle)} · ${esc(e.outcome.replaceAll('_',' '))}`).join('<br>'):'Simulator: no task executed.'}</div></div>${step.tools.length?`<details open><summary>${step.tools.length} permitted tool query</summary><pre>${esc(JSON.stringify(step.tools,null,2))}</pre></details>`:''}<details><summary>Actual requests, raw responses & validation (${calls.length} attempts)</summary>${calls.map(call=>`<p>Attempt ${call.attempt} · ${call.parse_error?'invalid output':call.transport_error?'transport error':'valid output'}</p><pre>${esc(JSON.stringify(call,null,2))}</pre>`).join('')}</details><details><summary>Full conversation before this step</summary><pre>${esc(JSON.stringify(step.agent_messages,null,2))}</pre></details><details><summary>Run details</summary><pre>${esc(JSON.stringify({mode:state.mode,source_mode:state.source_mode,run_id:c.run_id,model:c.model,provider:c.provider,prompt_sha256:c.prompt_hash,tokens:c.token_usage,reported_cost_usd:c.reported_cost_usd,retries:c.retry_count,invalid:c.invalid_attempt_count},null,2))}</pre></details>`;}
$('evalContent').innerHTML='<p class="muted">Hidden until you reveal a completed step.</p>';if(state.interruption_reason){$('error').textContent=state.interruption_reason;$('error').hidden=false;}modeChanged();}
async function action(fn){if(busy)return;busy=true;$('error').hidden=true;render();try{await fn();}catch(e){$('error').textContent=e.message;$('error').hidden=false;}finally{busy=false;render();}}
$('mode').onchange=modeChanged;$('start').onclick=()=>action(async()=>{const mode=$('mode').value;state=mode==='RECORDED'?await api('replay',{id:$('recording').value}):await api('start',{mode,scenario:$('scenario').value,confirm_live:$('confirmLive').checked});index=-1;});
$('next').onclick=()=>action(async()=>{state=await api('next',{});index=(state.visible_steps||0)-1;});$('reset').onclick=()=>action(async()=>{state=await api('reset',{});index=-1;});$('stepSelect').onchange=()=>{index=Number($('stepSelect').value);render();};
$('reveal').onclick=async()=>{try{const e=await api('reveal',{index});$('evalContent').innerHTML=['A0','A1'].map(c=>{const x=e.conditions[c];return `<div><p class="label">${c} · ${esc(e.mode)} · evaluator only</p><div class="metrics">${['tp','fp','fn'].map(k=>`<div class="metric">${k.toUpperCase()}<b>${x[k]}</b></div>`).join('')}</div><p class="muted">Missed: ${esc(x.missed.join(', ')||'none')}<br>False: ${esc(x.false.join(', ')||'none')}</p><details><summary>Evaluator task states and due set</summary><pre>${esc(JSON.stringify(x,null,2))}</pre></details></div>`;}).join('');}catch(e){$('error').hidden=false;$('error').textContent=e.message;}};
(async()=>{try{const data=await api('catalog');$('scenario').innerHTML=data.scenarios.map(s=>`<option value="${esc(s.id)}">${esc(s.title)}</option>`).join('');state=await api('state');index=(state.visible_steps||0)-1;render();modeChanged();}catch(e){$('error').hidden=false;$('error').textContent=e.message;}})();
